### ISSUE TITLE
Loss of gene ID when translating from Ensmbl to Entrez

### ISSUE THREAD

**Issue by JoseCorCab** [seoanezonjic/ExpHunterSuite#19]
Some genes are rejected when ID translation is performed, It's very important to control this situation

**Comment by jimrperkins** [comment]
If there is no ENTREZ id available for a given ENSEMBL Id, there is not much more we can do, at least not easily at the level of the translation for funciotnal enrichment. Does the poster has more ideas on how to control this situation?
