### ISSUE TITLE
Move or remove small functions in functional_report.Rmd

### ISSUE THREAD

**Issue by JoseCorCab** [seoanezonjic/ExpHunterSuite#32]
There are 2 functions defined in functional_report.Rmd (graph_file_name and exists_graph_file) thar are used only once in all functional hunter. In addition to this, these functions shouldn't be defined on report template, they should be defined in libraries and these functions take a functional_hunter.R variable (results_path) as default attribute. This is bad practice and it breaks when I try to render functional_report.Rmd in an independent way. I propose 2 options: 
i) Move the functions to a library file and change the default attribute to a string
ii) I recomend to remove this functions and use their raw code because they are used only once

**Comment by jimrperkins** [comment]
functional reports now does little more than call templates.
