### ISSUE TITLE
Output folders are being created by degenes_hunter function

### ISSUE THREAD

**Issue by fmjabato** [seoanezonjic/ExpHunterSuite#39]
remove dir.create(*) commands from main_degenes_hunter.R functions, This folders are being created empty and filled later by the script, but not by the function (which creates the folders too)

**Comment by seoanezonjic** [comment]
This issue can be resolved for perform_expression_analysis function, but coexpression involved functions need rework to avoid write output files. In the meantime dir.create calls are needed.

**Comment by seoanezonjic** [comment]
Waiting for coexpression function rework
